version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama_service
    volumes:
      - ./ollama_data_host:/root/.ollama
    ports:
      - "11434:11434"
    # Для использования GPU (NVIDIA):
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all 
    #           capabilities: [gpu]
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:11434/api/tags || exit 1"]
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  api_server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api_server_service
    depends_on:
      ollama:
        condition: service_healthy 
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env 
    restart: unless-stopped

# Именованный volume ollama_data больше не используется, так как мы используем bind mount
# volumes:
#   ollama_data: 